import unittest
from libs.numeros.number_to_text import Number2Text


class TestNumeroTexto(unittest.TestCase):
    numeros = [
        0,
        1,
        2,
        3,
        4,
        5,
        6,
        7,
        8,
        9,
        10,
        11,
        12,
        13,
        14,
        15,
        16,
        17,
        18,
        19,
        20,
        21,
        22,
        23,
        24,
        25,
        26,
        27,
        28,
        29,
        30,
        31,
        32,
        33,
        34,
        35,
        36,
        37,
        38,
        39,
        40,
        41,
        42,
        43,
        44,
        45,
        46,
        47,
        48,
        49,
        50,
        51,
        52,
        53,
        54,
        55,
        56,
        57,
        58,
        59,
        60,
        61,
        62,
        63,
        64,
        65,
        66,
        67,
        68,
        69,
        70,
        71,
        72,
        73,
        74,
        75,
        76,
        77,
        78,
        79,
        80,
        81,
        82,
        83,
        84,
        85,
        86,
        87,
        88,
        89,
        90,
        91,
        92,
        93,
        94,
        95,
        96,
        97,
        98,
        99,
        100
    ]

    salidas = [
        'cero',
        'uno',
        'dos',
        'tres',
        'cuatro',
        'cinco',
        'seis',
        'siete',
        'ocho',
        'nueve',
        'diez',
        'once',
        'doce',
        'trece',
        'catorce',
        'quince',
        'dieciseis',
        'diecisiete',
        'dieciocho',
        'diecinueve',
        'veinte',
        'veintiuno',
        'veintidos',
        'veintitres',
        'veinticuatro',
        'veinticinco',
        'veintiseis',
        'veintisiete',
        'veintiocho',
        'veintinueve',
        'treinta',
        'treinta y uno',
        'treinta y dos',
        'treinta y tres',
        'treinta y cuatro',
        'treinta y cinco',
        'treinta y seis',
        'treinta y siete',
        'treinta y ocho',
        'treinta y nueve',
        'cuarenta',
        'cuarenta y uno',
        'cuarenta y dos',
        'cuarenta y tres',
        'cuarenta y cuatro',
        'cuarenta y cinco',
        'cuarenta y seis',
        'cuarenta y siete',
        'cuarenta y ocho',
        'cuarenta y nueve',
        'cincuenta',
        'cincuenta y uno',
        'cincuenta y dos',
        'cincuenta y tres',
        'cincuenta y cuatro',
        'cincuenta y cinco',
        'cincuenta y seis',
        'cincuenta y siete',
        'cincuenta y ocho',
        'cincuenta y nueve',
        'sesenta',
        'sesenta y uno',
        'sesenta y dos',
        'sesenta y tres',
        'sesenta y cuatro',
        'sesenta y cinco',
        'sesenta y seis',
        'sesenta y siete',
        'sesenta y ocho',
        'sesenta y nueve',
        'setenta',
        'setenta y uno',
        'setenta y dos',
        'setenta y tres',
        'setenta y cuatro',
        'setenta y cinco',
        'setenta y seis',
        'setenta y siete',
        'setenta y ocho',
        'setenta y nueve',
        'ochenta',
        'ochenta y uno',
        'ochenta y dos',
        'ochenta y tres',
        'ochenta y cuatro',
        'ochenta y cinco',
        'ochenta y seis',
        'ochenta y siete',
        'ochenta y ocho',
        'ochenta y nueve',
        'noventa',
        'noventa y uno',
        'noventa y dos',
        'noventa y tres',
        'noventa y cuatro',
        'noventa y cinco',
        'noventa y seis',
        'noventa y siete',
        'noventa y ocho',
        'noventa y nueve',
        'cien'
        ]

    def test_numero_texto(self):
        obj = Number2Text()
        for item, numeros in enumerate(self.numeros):
            resultado = obj.convert(numeros)
            self.assertEqual(resultado, self.salidas[item])
        print('Finalizo...')


if __name__ == '__main__':
    unittest.main()
