import unittest
from libs.numeros.text_to_number_es import Text2NumberES

class TestTextoNumero(unittest.TestCase):


    literales = [
        'cero',
        'uno',
        'dos',
        'tres',
        'cuatro',
        'cinco',
        'seis',
        'siete',
        'ocho',
        'nueve',
        'diez',
        'once',
        'doce',
        'trece',
        'catorce',
        'quince',
        'dieciseis',
        'diecisiete',
        'dieciocho',
        'diecinueve',
        'veinte',
        'veinte y uno',
        'veinte y dos',
        'veinte y tres',
        'veinte y cuatro',
        'veinte y cinco',
        'veinte y seis',
        'veinte y siete',
        'veinte y ocho',
        'veinte y nueve',
        'treinta',
        'treinta y uno',
        'treinta y dos',
        'treinta y tres',
        'treinta y cuatro',
        'treinta y cinco',
        'treinta y seis',
        'treinta y siete',
        'treinta y ocho',
        'treinta y nueve',
        'cuarenta',
        'cuarenta y uno',
        'cuarenta y dos',
        'cuarenta y tres',
        'cuarenta y cuatro',
        'cuarenta y cinco',
        'cuarenta y seis',
        'cuarenta y siete',
        'cuarenta y ocho',
        'cuarenta y nueve',
        'cincuenta',
        'cincuenta y uno',
        'cincuenta y dos',
        'cincuenta y tres',
        'cincuenta y cuatro',
        'cincuenta y cinco',
        'cincuenta y seis',
        'cincuenta y siete',
        'cincuenta y ocho',
        'cincuenta y nueve',
        'sesenta',
        'sesenta y uno',
        'sesenta y dos',
        'sesenta y tres',
        'sesenta y cuatro',
        'sesenta y cinco',
        'sesenta y seis',
        'sesenta y siete',
        'sesenta y ocho',
        'sesenta y nueve',
        'setenta',
        'setenta y uno',
        'setenta y dos',
        'setenta y tres',
        'setenta y cuatro',
        'setenta y cinco',
        'setenta y seis',
        'setenta y siete',
        'setenta y ocho',
        'setenta y nueve',
        'ochenta',
        'ochenta y uno',
        'ochenta y dos',
        'ochenta y tres',
        'ochenta y cuatro',
        'ochenta y cinco',
        'ochenta y seis',
        'ochenta y siete',
        'ochenta y ocho',
        'ochenta y nueve',
        'noventa',
        'noventa y uno',
        'noventa y dos',
        'noventa y tres',
        'noventa y cuatro',
        'noventa y cinco',
        'noventa y seis',
        'noventa y siete',
        'noventa y ocho',
        'noventa y nueve',
        'cien',
        'ciento uno',
        'ciento dos',
        'ciento tres',
        'ciento cuatro',
        'ciento cinco',
        'ciento seis',
        'ciento siete',
        'ciento ocho',
        'ciento nueve',
        'ciento diez',
        'ciento once',
        'ciento doce',
        'ciento trece',
        'ciento catorce',
        'ciento quince',
        'ciento dieciseis',
        'ciento diecisiete',
        'ciento dieciocho',
        'ciento diecinueve',
        'ciento veinte',
        'ciento veintiuno',
        'ciento veintidos',
        'ciento veintitres',
        'ciento veinticuatro',
        'ciento veinticinco',
        'ciento veintiseis',
        'ciento veintisiete',
        'ciento veintiocho',
        'ciento veintinueve',
        'ciento treinta',
        'ciento treinta y uno',
        'ciento treinta y dos',
        'ciento treinta y tres',
        'ciento treinta y cuatro',
        'ciento treinta y cinco',
        'ciento treinta y seis',
        'ciento treinta y siete',
        'ciento treinta y ocho',
        'ciento treinta y nueve',
        'ciento cuarenta',
        'ciento cuarenta y Uno',
        'ciento cuarenta y dos',
        'ciento cuarenta y tres',
        'ciento cuarenta y cuatro',
        'ciento cuarenta y cinco',
        'ciento cuarenta y seis',
        'ciento cuarenta y siete',
        'ciento cuarenta y ocho',
        'ciento cuarenta y nueve',
        'ciento cincuenta',
        'ciento cincuenta y Uno',
        'ciento cincuenta y dos',
        'ciento cincuenta y tres',
        'ciento cincuenta y cuatro',
        'ciento cincuenta y cinco',
        'ciento cincuenta y seis',
        'ciento cincuenta y siete',
        'ciento cincuenta y ocho',
        'ciento cincuenta y nueve',
        'ciento sesenta',
        'ciento sesenta y Uno',
        'ciento sesenta y dos',
        'ciento sesenta y tres',
        'ciento sesenta y cuatro',
        'ciento sesenta y cinco',
        'ciento sesenta y seis',
        'ciento sesenta y siete',
        'ciento sesenta y ocho',
        'ciento sesenta y nueve',
        'ciento setenta',
        'ciento setenta y Uno',
        'ciento setenta y dos',
        'ciento setenta y tres',
        'ciento setenta y cuatro',
        'ciento setenta y cinco',
        'ciento setenta y seis',
        'ciento setenta y siete',
        'ciento setenta y ocho',
        'ciento setenta y nueve',
        'ciento ochenta',
        'ciento ochenta y Uno',
        'ciento ochenta y dos',
        'ciento ochenta y tres',
        'ciento ochenta y cuatro',
        'ciento ochenta y cinco',
        'ciento ochenta y seis',
        'ciento ochenta y siete',
        'ciento ochenta y ocho',
        'ciento ochenta y nueve',
        'ciento noventa',
        'ciento noventa y Uno',
        'ciento noventa y dos',
        'ciento noventa y tres',
        'ciento noventa y cuatro',
        'ciento noventa y cinco',
        'ciento noventa y seis',
        'ciento noventa y siete',
        'ciento noventa y ocho',
        'ciento noventa y nueve',
        'doscientos',
        'doscientos Uno',
        'doscientos dos',
        'doscientos tres',
        'doscientos cuatro',
        'doscientos cinco',
        'doscientos seis',
        'doscientos siete',
        'doscientos ocho',
        'doscientos nueve',
        'doscientos diez',
        'doscientos once',
        'doscientos doce',
        'doscientos trece',
        'doscientos catorce',
        'doscientos quince',
        'doscientos dieciseis',
        'doscientos diecisiete',
        'doscientos dieciocho',
        'doscientos diecinueve',
        'doscientos veinte',
        'doscientos veintiuno',
        'doscientos veintidos',
        'doscientos veintitres',
        'doscientos veinticuatro',
        'doscientos veinticinco',
        'doscientos veintiseis',
        'doscientos veintisiete',
        'doscientos veintiocho',
        'doscientos veintinueve',
        'doscientos treinta',
        'doscientos treinta y Uno',
        'doscientos treinta y dos',
        'doscientos treinta y tres',
        'doscientos treinta y cuatro',
        'doscientos treinta y cinco',
        'doscientos treinta y seis',
        'doscientos treinta y siete',
        'doscientos treinta y ocho',
        'doscientos treinta y nueve',
        'doscientos cuarenta',
        'doscientos cuarenta y Uno',
        'doscientos cuarenta y dos',
        'doscientos cuarenta y tres',
        'doscientos cuarenta y cuatro',
        'doscientos cuarenta y cinco',
        'doscientos cuarenta y seis',
        'doscientos cuarenta y siete',
        'doscientos cuarenta y ocho',
        'doscientos cuarenta y nueve',
        'doscientos cincuenta',
        'doscientos cincuenta y Uno',
        'doscientos cincuenta y dos',
        'doscientos cincuenta y tres',
        'doscientos cincuenta y cuatro',
        'doscientos cincuenta y cinco',
        'doscientos cincuenta y seis',
        'doscientos cincuenta y siete',
        'doscientos cincuenta y ocho',
        'doscientos cincuenta y nueve',
        'doscientos sesenta',
        'doscientos sesenta y Uno',
        'doscientos sesenta y dos',
        'doscientos sesenta y tres',
        'doscientos sesenta y cuatro',
        'doscientos sesenta y cinco',
        'doscientos sesenta y seis',
        'doscientos sesenta y siete',
        'doscientos sesenta y ocho',
        'doscientos sesenta y nueve',
        'doscientos setenta',
        'doscientos setenta y Uno',
        'doscientos setenta y dos',
        'doscientos setenta y tres',
        'doscientos setenta y cuatro',
        'doscientos setenta y cinco',
        'doscientos setenta y seis',
        'doscientos setenta y siete',
        'doscientos setenta y ocho',
        'doscientos setenta y nueve',
        'doscientos ochenta',
        'doscientos ochenta y Uno',
        'doscientos ochenta y dos',
        'doscientos ochenta y tres',
        'doscientos ochenta y cuatro',
        'doscientos ochenta y cinco',
        'doscientos ochenta y seis',
        'doscientos ochenta y siete',
        'doscientos ochenta y ocho',
        'doscientos ochenta y nueve',
        'doscientos noventa',
        'doscientos noventa y Uno',
        'doscientos noventa y dos',
        'doscientos noventa y tres',
        'doscientos noventa y cuatro',
        'doscientos noventa y cinco',
        'doscientos noventa y seis',
        'doscientos noventa y siete',
        'doscientos noventa y ocho',
        'doscientos noventa y nueve',
        'trescientos',
        'trescientos Uno',
        'trescientos dos',
        'trescientos tres',
        'trescientos cuatro',
        'trescientos cinco',
        'trescientos seis',
        'trescientos siete',
        'trescientos ocho',
        'trescientos nueve',
        'trescientos diez',
        'trescientos once',
        'trescientos doce',
        'trescientos trece',
        'trescientos catorce',
        'trescientos quince',
        'trescientos dieciseis',
        'trescientos diecisiete',
        'trescientos dieciocho',
        'trescientos diecinueve',
        'trescientos veinte',
        'trescientos veintiuno',
        'trescientos veintidos',
        'trescientos veintitres',
        'trescientos veinticuatro',
        'trescientos veinticinco',
        'trescientos veintiseis',
        'trescientos veintisiete',
        'trescientos veintiocho',
        'trescientos veintinueve',
        'trescientos treinta',
        'trescientos treinta y Uno',
        'trescientos treinta y dos',
        'trescientos treinta y tres',
        'trescientos treinta y cuatro',
        'trescientos treinta y cinco',
        'trescientos treinta y seis',
        'trescientos treinta y siete',
        'trescientos treinta y ocho',
        'trescientos treinta y nueve',
        'trescientos cuarenta',
        'trescientos cuarenta y Uno',
        'trescientos cuarenta y dos',
        'trescientos cuarenta y tres',
        'trescientos cuarenta y cuatro',
        'trescientos cuarenta y cinco',
        'trescientos cuarenta y seis',
        'trescientos cuarenta y siete',
        'trescientos cuarenta y ocho',
        'trescientos cuarenta y nueve',
        'trescientos cincuenta',
        'trescientos cincuenta y Uno',
        'trescientos cincuenta y dos',
        'trescientos cincuenta y tres',
        'trescientos cincuenta y cuatro',
        'trescientos cincuenta y cinco',
        'trescientos cincuenta y seis',
        'trescientos cincuenta y siete',
        'trescientos cincuenta y ocho',
        'trescientos cincuenta y nueve',
        'trescientos sesenta',
        'trescientos sesenta y Uno',
        'trescientos sesenta y dos',
        'trescientos sesenta y tres',
        'trescientos sesenta y cuatro',
        'trescientos sesenta y cinco',
        'trescientos sesenta y seis',
        'trescientos sesenta y siete',
        'trescientos sesenta y ocho',
        'trescientos sesenta y nueve',
        'trescientos setenta',
        'trescientos setenta y Uno',
        'trescientos setenta y dos',
        'trescientos setenta y tres',
        'trescientos setenta y cuatro',
        'trescientos setenta y cinco',
        'trescientos setenta y seis',
        'trescientos setenta y siete',
        'trescientos setenta y ocho',
        'trescientos setenta y nueve',
        'trescientos ochenta',
        'trescientos ochenta y Uno',
        'trescientos ochenta y dos',
        'trescientos ochenta y tres',
        'trescientos ochenta y cuatro',
        'trescientos ochenta y cinco',
        'trescientos ochenta y seis',
        'trescientos ochenta y siete',
        'trescientos ochenta y ocho',
        'trescientos ochenta y nueve',
        'trescientos noventa',
        'trescientos noventa y Uno',
        'trescientos noventa y dos',
        'trescientos noventa y tres',
        'trescientos noventa y cuatro',
        'trescientos noventa y cinco',
        'trescientos noventa y seis',
        'trescientos noventa y siete',
        'trescientos noventa y ocho',
        'trescientos noventa y nueve',
        'cuatrocientos',
        'cuatrocientos Uno',
        'cuatrocientos dos',
        'cuatrocientos tres',
        'cuatrocientos cuatro',
        'cuatrocientos cinco',
        'cuatrocientos seis',
        'cuatrocientos siete',
        'cuatrocientos ocho',
        'cuatrocientos nueve',
        'cuatrocientos diez',
        'cuatrocientos once',
        'cuatrocientos doce',
        'cuatrocientos trece',
        'cuatrocientos catorce',
        'cuatrocientos quince',
        'cuatrocientos dieciseis',
        'cuatrocientos diecisiete',
        'cuatrocientos dieciocho',
        'cuatrocientos diecinueve',
        'cuatrocientos veinte',
        'cuatrocientos veintiuno',
        'cuatrocientos veintidos',
        'cuatrocientos veintitres',
        'cuatrocientos veinticuatro',
        'cuatrocientos veinticinco',
        'cuatrocientos veintiseis',
        'cuatrocientos veintisiete',
        'cuatrocientos veintiocho',
        'cuatrocientos veintinueve',
        'cuatrocientos treinta',
        'cuatrocientos treinta y Uno',
        'cuatrocientos treinta y dos',
        'cuatrocientos treinta y tres',
        'cuatrocientos treinta y cuatro',
        'cuatrocientos treinta y cinco',
        'cuatrocientos treinta y seis',
        'cuatrocientos treinta y siete',
        'cuatrocientos treinta y ocho',
        'cuatrocientos treinta y nueve',
        'cuatrocientos cuarenta',
        'cuatrocientos cuarenta y Uno',
        'cuatrocientos cuarenta y dos',
        'cuatrocientos cuarenta y tres',
        'cuatrocientos cuarenta y cuatro',
        'cuatrocientos cuarenta y cinco',
        'cuatrocientos cuarenta y seis',
        'cuatrocientos cuarenta y siete',
        'cuatrocientos cuarenta y ocho',
        'cuatrocientos cuarenta y nueve',
        'cuatrocientos cincuenta',
        'cuatrocientos cincuenta y Uno',
        'cuatrocientos cincuenta y dos',
        'cuatrocientos cincuenta y tres',
        'cuatrocientos cincuenta y cuatro',
        'cuatrocientos cincuenta y cinco',
        'cuatrocientos cincuenta y seis',
        'cuatrocientos cincuenta y siete',
        'cuatrocientos cincuenta y ocho',
        'cuatrocientos cincuenta y nueve',
        'cuatrocientos sesenta',
        'cuatrocientos sesenta y Uno',
        'cuatrocientos sesenta y dos',
        'cuatrocientos sesenta y tres',
        'cuatrocientos sesenta y cuatro',
        'cuatrocientos sesenta y cinco',
        'cuatrocientos sesenta y seis',
        'cuatrocientos sesenta y siete',
        'cuatrocientos sesenta y ocho',
        'cuatrocientos sesenta y nueve',
        'cuatrocientos setenta',
        'cuatrocientos setenta y Uno',
        'cuatrocientos setenta y dos',
        'cuatrocientos setenta y tres',
        'cuatrocientos setenta y cuatro',
        'cuatrocientos setenta y cinco',
        'cuatrocientos setenta y seis',
        'cuatrocientos setenta y siete',
        'cuatrocientos setenta y ocho',
        'cuatrocientos setenta y nueve',
        'cuatrocientos ochenta',
        'cuatrocientos ochenta y Uno',
        'cuatrocientos ochenta y dos',
        'cuatrocientos ochenta y tres',
        'cuatrocientos ochenta y cuatro',
        'cuatrocientos ochenta y cinco',
        'cuatrocientos ochenta y seis',
        'cuatrocientos ochenta y siete',
        'cuatrocientos ochenta y ocho',
        'cuatrocientos ochenta y nueve',
        'cuatrocientos noventa',
        'cuatrocientos noventa y Uno',
        'cuatrocientos noventa y dos',
        'cuatrocientos noventa y tres',
        'cuatrocientos noventa y cuatro',
        'cuatrocientos noventa y cinco',
        'cuatrocientos noventa y seis',
        'cuatrocientos noventa y siete',
        'cuatrocientos noventa y ocho',
        'cuatrocientos noventa y nueve',
        'quinientos',
        'quinientos Uno',
        'quinientos dos',
        'quinientos tres',
        'quinientos cuatro',
        'quinientos cinco',
        'quinientos seis',
        'quinientos siete',
        'quinientos ocho',
        'quinientos nueve',
        'quinientos diez',
        'quinientos once',
        'quinientos doce',
        'quinientos trece',
        'quinientos catorce',
        'quinientos quince',
        'quinientos dieciseis',
        'quinientos diecisiete',
        'quinientos dieciocho',
        'quinientos diecinueve',
        'quinientos veinte',
        'quinientos veintiuno',
        'quinientos veintidos',
        'quinientos veintitres',
        'quinientos veinticuatro',
        'quinientos veinticinco',
        'quinientos veintiseis',
        'quinientos veintisiete',
        'quinientos veintiocho',
        'quinientos veintinueve',
        'quinientos treinta',
        'quinientos treinta y Uno',
        'quinientos treinta y dos',
        'quinientos treinta y tres',
        'quinientos treinta y cuatro',
        'quinientos treinta y cinco',
        'quinientos treinta y seis',
        'quinientos treinta y siete',
        'quinientos treinta y ocho',
        'quinientos treinta y nueve',
        'quinientos cuarenta',
        'quinientos cuarenta y Uno',
        'quinientos cuarenta y dos',
        'quinientos cuarenta y tres',
        'quinientos cuarenta y cuatro',
        'quinientos cuarenta y cinco',
        'quinientos cuarenta y seis',
        'quinientos cuarenta y siete',
        'quinientos cuarenta y ocho',
        'quinientos cuarenta y nueve',
        'quinientos cincuenta',
        'quinientos cincuenta y Uno',
        'quinientos cincuenta y dos',
        'quinientos cincuenta y tres',
        'quinientos cincuenta y cuatro',
        'quinientos cincuenta y cinco',
        'quinientos cincuenta y seis',
        'quinientos cincuenta y siete',
        'quinientos cincuenta y ocho',
        'quinientos cincuenta y nueve',
        'quinientos sesenta',
        'quinientos sesenta y Uno',
        'quinientos sesenta y dos',
        'quinientos sesenta y tres',
        'quinientos sesenta y cuatro',
        'quinientos sesenta y cinco',
        'quinientos sesenta y seis',
        'quinientos sesenta y siete',
        'quinientos sesenta y ocho',
        'quinientos sesenta y nueve',
        'quinientos setenta',
        'quinientos setenta y Uno',
        'quinientos setenta y dos',
        'quinientos setenta y tres',
        'quinientos setenta y cuatro',
        'quinientos setenta y cinco',
        'quinientos setenta y seis',
        'quinientos setenta y siete',
        'quinientos setenta y ocho',
        'quinientos setenta y nueve',
        'quinientos ochenta',
        'quinientos ochenta y Uno',
        'quinientos ochenta y dos',
        'quinientos ochenta y tres',
        'quinientos ochenta y cuatro',
        'quinientos ochenta y cinco',
        'quinientos ochenta y seis',
        'quinientos ochenta y siete',
        'quinientos ochenta y ocho',
        'quinientos ochenta y nueve',
        'quinientos noventa',
        'quinientos noventa y Uno',
        'quinientos noventa y dos',
        'quinientos noventa y tres',
        'quinientos noventa y cuatro',
        'quinientos noventa y cinco',
        'quinientos noventa y seis',
        'quinientos noventa y siete',
        'quinientos noventa y ocho',
        'quinientos noventa y nueve',
        'seiscientos',
        'seiscientos Uno',
        'seiscientos dos',
        'seiscientos tres',
        'seiscientos cuatro',
        'seiscientos cinco',
        'seiscientos seis',
        'seiscientos siete',
        'seiscientos ocho',
        'seiscientos nueve',
        'seiscientos diez',
        'seiscientos once',
        'seiscientos doce',
        'seiscientos trece',
        'seiscientos catorce',
        'seiscientos quince',
        'seiscientos dieciseis',
        'seiscientos diecisiete',
        'seiscientos dieciocho',
        'seiscientos diecinueve',
        'seiscientos veinte',
        'seiscientos veintiuno',
        'seiscientos veintidos',
        'seiscientos veintitres',
        'seiscientos veinticuatro',
        'seiscientos veinticinco',
        'seiscientos veintiseis',
        'seiscientos veintisiete',
        'seiscientos veintiocho',
        'seiscientos veintinueve',
        'seiscientos treinta',
        'seiscientos treinta y Uno',
        'seiscientos treinta y dos',
        'seiscientos treinta y tres',
        'seiscientos treinta y cuatro',
        'seiscientos treinta y cinco',
        'seiscientos treinta y seis',
        'seiscientos treinta y siete',
        'seiscientos treinta y ocho',
        'seiscientos treinta y nueve',
        'seiscientos cuarenta',
        'seiscientos cuarenta y Uno',
        'seiscientos cuarenta y dos',
        'seiscientos cuarenta y tres',
        'seiscientos cuarenta y cuatro',
        'seiscientos cuarenta y cinco',
        'seiscientos cuarenta y seis',
        'seiscientos cuarenta y siete',
        'seiscientos cuarenta y ocho',
        'seiscientos cuarenta y nueve',
        'seiscientos cincuenta',
        'seiscientos cincuenta y Uno',
        'seiscientos cincuenta y dos',
        'seiscientos cincuenta y tres',
        'seiscientos cincuenta y cuatro',
        'seiscientos cincuenta y cinco',
        'seiscientos cincuenta y seis',
        'seiscientos cincuenta y siete',
        'seiscientos cincuenta y ocho',
        'seiscientos cincuenta y nueve',
        'seiscientos sesenta',
        'seiscientos sesenta y Uno',
        'seiscientos sesenta y dos',
        'seiscientos sesenta y tres',
        'seiscientos sesenta y cuatro',
        'seiscientos sesenta y cinco',
        'seiscientos sesenta y seis',
        'seiscientos sesenta y siete',
        'seiscientos sesenta y ocho',
        'seiscientos sesenta y nueve',
        'seiscientos setenta',
        'seiscientos setenta y Uno',
        'seiscientos setenta y dos',
        'seiscientos setenta y tres',
        'seiscientos setenta y cuatro',
        'seiscientos setenta y cinco',
        'seiscientos setenta y seis',
        'seiscientos setenta y siete',
        'seiscientos setenta y ocho',
        'seiscientos setenta y nueve',
        'seiscientos ochenta',
        'seiscientos ochenta y Uno',
        'seiscientos ochenta y dos',
        'seiscientos ochenta y tres',
        'seiscientos ochenta y cuatro',
        'seiscientos ochenta y cinco',
        'seiscientos ochenta y seis',
        'seiscientos ochenta y siete',
        'seiscientos ochenta y ocho',
        'seiscientos ochenta y nueve',
        'seiscientos noventa',
        'seiscientos noventa y Uno',
        'seiscientos noventa y dos',
        'seiscientos noventa y tres',
        'seiscientos noventa y cuatro',
        'seiscientos noventa y cinco',
        'seiscientos noventa y seis',
        'seiscientos noventa y siete',
        'seiscientos noventa y ocho',
        'seiscientos noventa y nueve',
        'setecientos',
        'setecientos Uno',
        'setecientos dos',
        'setecientos tres',
        'setecientos cuatro',
        'setecientos cinco',
        'setecientos seis',
        'setecientos siete',
        'setecientos ocho',
        'setecientos nueve',
        'setecientos diez',
        'setecientos once',
        'setecientos doce',
        'setecientos trece',
        'setecientos catorce',
        'setecientos quince',
        'setecientos dieciseis',
        'setecientos diecisiete',
        'setecientos dieciocho',
        'setecientos diecinueve',
        'setecientos veinte',
        'setecientos veintiuno',
        'setecientos veintidos',
        'setecientos veintitres',
        'setecientos veinticuatro',
        'setecientos veinticinco',
        'setecientos veintiseis',
        'setecientos veintisiete',
        'setecientos veintiocho',
        'setecientos veintinueve',
        'setecientos treinta',
        'setecientos treinta y Uno',
        'setecientos treinta y dos',
        'setecientos treinta y tres',
        'setecientos treinta y cuatro',
        'setecientos treinta y cinco',
        'setecientos treinta y seis',
        'setecientos treinta y siete',
        'setecientos treinta y ocho',
        'setecientos treinta y nueve',
        'setecientos cuarenta',
        'setecientos cuarenta y Uno',
        'setecientos cuarenta y dos',
        'setecientos cuarenta y tres',
        'setecientos cuarenta y cuatro',
        'setecientos cuarenta y cinco',
        'setecientos cuarenta y seis',
        'setecientos cuarenta y siete',
        'setecientos cuarenta y ocho',
        'setecientos cuarenta y nueve',
        'setecientos cincuenta',
        'setecientos cincuenta y Uno',
        'setecientos cincuenta y dos',
        'setecientos cincuenta y tres',
        'setecientos cincuenta y cuatro',
        'setecientos cincuenta y cinco',
        'setecientos cincuenta y seis',
        'setecientos cincuenta y siete',
        'setecientos cincuenta y ocho',
        'setecientos cincuenta y nueve',
        'setecientos sesenta',
        'setecientos sesenta y Uno',
        'setecientos sesenta y dos',
        'setecientos sesenta y tres',
        'setecientos sesenta y cuatro',
        'setecientos sesenta y cinco',
        'setecientos sesenta y seis',
        'setecientos sesenta y siete',
        'setecientos sesenta y ocho',
        'setecientos sesenta y nueve',
        'setecientos setenta',
        'setecientos setenta y Uno',
        'setecientos setenta y dos',
        'setecientos setenta y tres',
        'setecientos setenta y cuatro',
        'setecientos setenta y cinco',
        'setecientos setenta y seis',
        'setecientos setenta y siete',
        'setecientos setenta y ocho',
        'setecientos setenta y nueve',
        'setecientos ochenta',
        'setecientos ochenta y Uno',
        'setecientos ochenta y dos',
        'setecientos ochenta y tres',
        'setecientos ochenta y cuatro',
        'setecientos ochenta y cinco',
        'setecientos ochenta y seis',
        'setecientos ochenta y siete',
        'setecientos ochenta y ocho',
        'setecientos ochenta y nueve',
        'setecientos noventa',
        'setecientos noventa y Uno',
        'setecientos noventa y dos',
        'setecientos noventa y tres',
        'setecientos noventa y cuatro',
        'setecientos noventa y cinco',
        'setecientos noventa y seis',
        'setecientos noventa y siete',
        'setecientos noventa y ocho',
        'setecientos noventa y nueve',
        'ochocientos',
        'ochocientos Uno',
        'ochocientos dos',
        'ochocientos tres',
        'ochocientos cuatro',
        'ochocientos cinco',
        'ochocientos seis',
        'ochocientos siete',
        'ochocientos ocho',
        'ochocientos nueve',
        'ochocientos diez',
        'ochocientos once',
        'ochocientos doce',
        'ochocientos trece',
        'ochocientos catorce',
        'ochocientos quince',
        'ochocientos dieciseis',
        'ochocientos diecisiete',
        'ochocientos dieciocho',
        'ochocientos diecinueve',
        'ochocientos veinte',
        'ochocientos veintiuno',
        'ochocientos veintidos',
        'ochocientos veintitres',
        'ochocientos veinticuatro',
        'ochocientos veinticinco',
        'ochocientos veintiseis',
        'ochocientos veintisiete',
        'ochocientos veintiocho',
        'ochocientos veintinueve',
        'ochocientos treinta',
        'ochocientos treinta y Uno',
        'ochocientos treinta y dos',
        'ochocientos treinta y tres',
        'ochocientos treinta y cuatro',
        'ochocientos treinta y cinco',
        'ochocientos treinta y seis',
        'ochocientos treinta y siete',
        'ochocientos treinta y ocho',
        'ochocientos treinta y nueve',
        'ochocientos cuarenta',
        'ochocientos cuarenta y Uno',
        'ochocientos cuarenta y dos',
        'ochocientos cuarenta y tres',
        'ochocientos cuarenta y cuatro',
        'ochocientos cuarenta y cinco',
        'ochocientos cuarenta y seis',
        'ochocientos cuarenta y siete',
        'ochocientos cuarenta y ocho',
        'ochocientos cuarenta y nueve',
        'ochocientos cincuenta',
        'ochocientos cincuenta y Uno',
        'ochocientos cincuenta y dos',
        'ochocientos cincuenta y tres',
        'ochocientos cincuenta y cuatro',
        'ochocientos cincuenta y cinco',
        'ochocientos cincuenta y seis',
        'ochocientos cincuenta y siete',
        'ochocientos cincuenta y ocho',
        'ochocientos cincuenta y nueve',
        'ochocientos sesenta',
        'ochocientos sesenta y Uno',
        'ochocientos sesenta y dos',
        'ochocientos sesenta y tres',
        'ochocientos sesenta y cuatro',
        'ochocientos sesenta y cinco',
        'ochocientos sesenta y seis',
        'ochocientos sesenta y siete',
        'ochocientos sesenta y ocho',
        'ochocientos sesenta y nueve',
        'ochocientos setenta',
        'ochocientos setenta y Uno',
        'ochocientos setenta y dos',
        'ochocientos setenta y tres',
        'ochocientos setenta y cuatro',
        'ochocientos setenta y cinco',
        'ochocientos setenta y seis',
        'ochocientos setenta y siete',
        'ochocientos setenta y ocho',
        'ochocientos setenta y nueve',
        'ochocientos ochenta',
        'ochocientos ochenta y Uno',
        'ochocientos ochenta y dos',
        'ochocientos ochenta y tres',
        'ochocientos ochenta y cuatro',
        'ochocientos ochenta y cinco',
        'ochocientos ochenta y seis',
        'ochocientos ochenta y siete',
        'ochocientos ochenta y ocho',
        'ochocientos ochenta y nueve',
        'ochocientos noventa',
        'ochocientos noventa y Uno',
        'ochocientos noventa y dos',
        'ochocientos noventa y tres',
        'ochocientos noventa y cuatro',
        'ochocientos noventa y cinco',
        'ochocientos noventa y seis',
        'ochocientos noventa y siete',
        'ochocientos noventa y ocho',
        'ochocientos noventa y nueve',
        'novecientos',
        'novecientos Uno',
        'novecientos dos',
        'novecientos tres',
        'novecientos cuatro',
        'novecientos cinco',
        'novecientos seis',
        'novecientos siete',
        'novecientos ocho',
        'novecientos nueve',
        'novecientos diez',
        'novecientos once',
        'novecientos doce',
        'novecientos trece',
        'novecientos catorce',
        'novecientos quince',
        'novecientos dieciseis',
        'novecientos diecisiete',
        'novecientos dieciocho',
        'novecientos diecinueve',
        'novecientos veinte',
        'novecientos veintiuno',
        'novecientos veintidos',
        'novecientos veintitres',
        'novecientos veinticuatro',
        'novecientos veinticinco',
        'novecientos veintiseis',
        'novecientos veintisiete',
        'novecientos veintiocho',
        'novecientos veintinueve',
        'novecientos treinta',
        'novecientos treinta y Uno',
        'novecientos treinta y dos',
        'novecientos treinta y tres',
        'novecientos treinta y cuatro',
        'novecientos treinta y cinco',
        'novecientos treinta y seis',
        'novecientos treinta y siete',
        'novecientos treinta y ocho',
        'novecientos treinta y nueve',
        'novecientos cuarenta',
        'novecientos cuarenta y Uno',
        'novecientos cuarenta y dos',
        'novecientos cuarenta y tres',
        'novecientos cuarenta y cuatro',
        'novecientos cuarenta y cinco',
        'novecientos cuarenta y seis',
        'novecientos cuarenta y siete',
        'novecientos cuarenta y ocho',
        'novecientos cuarenta y nueve',
        'novecientos cincuenta',
        'novecientos cincuenta y Uno',
        'novecientos cincuenta y dos',
        'novecientos cincuenta y tres',
        'novecientos cincuenta y cuatro',
        'novecientos cincuenta y cinco',
        'novecientos cincuenta y seis',
        'novecientos cincuenta y siete',
        'novecientos cincuenta y ocho',
        'novecientos cincuenta y nueve',
        'novecientos sesenta',
        'novecientos sesenta y Uno',
        'novecientos sesenta y dos',
        'novecientos sesenta y tres',
        'novecientos sesenta y cuatro',
        'novecientos sesenta y cinco',
        'novecientos sesenta y seis',
        'novecientos sesenta y siete',
        'novecientos sesenta y ocho',
        'novecientos sesenta y nueve',
        'novecientos setenta',
        'novecientos setenta y Uno',
        'novecientos setenta y dos',
        'novecientos setenta y tres',
        'novecientos setenta y cuatro',
        'novecientos setenta y cinco',
        'novecientos setenta y seis',
        'novecientos setenta y siete',
        'novecientos setenta y ocho',
        'novecientos setenta y nueve',
        'novecientos ochenta',
        'novecientos ochenta y Uno',
        'novecientos ochenta y dos',
        'novecientos ochenta y tres',
        'novecientos ochenta y cuatro',
        'novecientos ochenta y cinco',
        'novecientos ochenta y seis',
        'novecientos ochenta y siete',
        'novecientos ochenta y ocho',
        'novecientos ochenta y nueve',
        'novecientos noventa',
        'novecientos noventa y uno',
        'novecientos noventa y dos',
        'novecientos noventa y tres',
        'novecientos noventa y cuatro',
        'novecientos noventa y cinco',
        'novecientos noventa y seis',
        'novecientos noventa y siete',
        'novecientos noventa y ocho',
        'novecientos noventa y nueve',
        'mil'
        ]


    salidas = [
        ['0'],
        ['1'],
        ['2'],
        ['3'],
        ['4'],
        ['5'],
        ['6'],
        ['7'],
        ['8'],
        ['9'],
        ['10'],
        ['11'],
        ['12'],
        ['13'],
        ['14'],
        ['15'],
        ['16'],
        ['17'],
        ['18'],
        ['19'],
        ['20'],
        ['20', 'y', '1'],
        ['20', 'y', '2'],
        ['20', 'y', '3'],
        ['20', 'y', '4'],
        ['20', 'y', '5'],
        ['20', 'y', '6'],
        ['20', 'y', '7'],
        ['20', 'y', '8'],
        ['20', 'y', '9'],
        ['30'],
        ['30', 'y', '1'],
        ['30', 'y', '2'],
        ['30', 'y', '3'],
        ['30', 'y', '4'],
        ['30', 'y', '5'],
        ['30', 'y', '6'],
        ['30', 'y', '7'],
        ['30', 'y', '8'],
        ['30', 'y', '9'],
        ['40'],
        ['40', 'y', '1'],
        ['40', 'y', '2'],
        ['40', 'y', '3'],
        ['40', 'y', '4'],
        ['40', 'y', '5'],
        ['40', 'y', '6'],
        ['40', 'y', '7'],
        ['40', 'y', '8'],
        ['40', 'y', '9'],
        ['50'],
        ['50', 'y', '1'],
        ['50', 'y', '2'],
        ['50', 'y', '3'],
        ['50', 'y', '4'],
        ['50', 'y', '5'],
        ['50', 'y', '6'],
        ['50', 'y', '7'],
        ['50', 'y', '8'],
        ['50', 'y', '9'],
        ['60'],
        ['60', 'y', '1'],
        ['60', 'y', '2'],
        ['60', 'y', '3'],
        ['60', 'y', '4'],
        ['60', 'y', '5'],
        ['60', 'y', '6'],
        ['60', 'y', '7'],
        ['60', 'y', '8'],
        ['60', 'y', '9'],
        ['70'],
        ['70', 'y', '1'],
        ['70', 'y', '2'],
        ['70', 'y', '3'],
        ['70', 'y', '4'],
        ['70', 'y', '5'],
        ['70', 'y', '6'],
        ['70', 'y', '7'],
        ['70', 'y', '8'],
        ['70', 'y', '9'],
        ['80'],
        ['80', 'y', '1'],
        ['80', 'y', '2'],
        ['80', 'y', '3'],
        ['80', 'y', '4'],
        ['80', 'y', '5'],
        ['80', 'y', '6'],
        ['80', 'y', '7'],
        ['80', 'y', '8'],
        ['80', 'y', '9'],
        ['90'],
        ['90', 'y', '1'],
        ['90', 'y', '2'],
        ['90', 'y', '3'],
        ['90', 'y', '4'],
        ['90', 'y', '5'],
        ['90', 'y', '6'],
        ['90', 'y', '7'],
        ['90', 'y', '8'],
        ['90', 'y', '9'],
        ['100'],
        ['100', '1'],
        ['100', '2'],
        ['100', '3'],
        ['100', '4'],
        ['100', '5'],
        ['100', '6'],
        ['100', '7'],
        ['100', '8'],
        ['100', '9'],
        ['100', '10'],
        ['100', '11'],
        ['100', '12'],
        ['100', '13'],
        ['100', '14'],
        ['100', '15'],
        ['100', '16'],
        ['100', '17'],
        ['100', '18'],
        ['100', '19'],
        ['100', '20'],
        ['100', '21'],
        ['100', '22'],
        ['100', '23'],
        ['100', '24'],
        ['100', '25'],
        ['100', '26'],
        ['100', '27'],
        ['100', '28'],
        ['100', '29'],
        ['100', '30'],
        ['100', '30', 'y', '1'],
        ['100', '30', 'y', '2'],
        ['100', '30', 'y', '3'],
        ['100', '30', 'y', '4'],
        ['100', '30', 'y', '5'],
        ['100', '30', 'y', '6'],
        ['100', '30', 'y', '7'],
        ['100', '30', 'y', '8'],
        ['100', '30', 'y', '9'],
        ['100', '40'],
        ['100', '40', 'y', '1'],
        ['100', '40', 'y', '2'],
        ['100', '40', 'y', '3'],
        ['100', '40', 'y', '4'],
        ['100', '40', 'y', '5'],
        ['100', '40', 'y', '6'],
        ['100', '40', 'y', '7'],
        ['100', '40', 'y', '8'],
        ['100', '40', 'y', '9'],
        ['100', '50'],
        ['100', '50', 'y', '1'],
        ['100', '50', 'y', '2'],
        ['100', '50', 'y', '3'],
        ['100', '50', 'y', '4'],
        ['100', '50', 'y', '5'],
        ['100', '50', 'y', '6'],
        ['100', '50', 'y', '7'],
        ['100', '50', 'y', '8'],
        ['100', '50', 'y', '9'],
        ['100', '60'],
        ['100', '60', 'y', '1'],
        ['100', '60', 'y', '2'],
        ['100', '60', 'y', '3'],
        ['100', '60', 'y', '4'],
        ['100', '60', 'y', '5'],
        ['100', '60', 'y', '6'],
        ['100', '60', 'y', '7'],
        ['100', '60', 'y', '8'],
        ['100', '60', 'y', '9'],
        ['100', '70'],
        ['100', '70', 'y', '1'],
        ['100', '70', 'y', '2'],
        ['100', '70', 'y', '3'],
        ['100', '70', 'y', '4'],
        ['100', '70', 'y', '5'],
        ['100', '70', 'y', '6'],
        ['100', '70', 'y', '7'],
        ['100', '70', 'y', '8'],
        ['100', '70', 'y', '9'],
        ['100', '80'],
        ['100', '80', 'y', '1'],
        ['100', '80', 'y', '2'],
        ['100', '80', 'y', '3'],
        ['100', '80', 'y', '4'],
        ['100', '80', 'y', '5'],
        ['100', '80', 'y', '6'],
        ['100', '80', 'y', '7'],
        ['100', '80', 'y', '8'],
        ['100', '80', 'y', '9'],
        ['100', '90'],
        ['100', '90', 'y', '1'],
        ['100', '90', 'y', '2'],
        ['100', '90', 'y', '3'],
        ['100', '90', 'y', '4'],
        ['100', '90', 'y', '5'],
        ['100', '90', 'y', '6'],
        ['100', '90', 'y', '7'],
        ['100', '90', 'y', '8'],
        ['100', '90', 'y', '9'],
        ['200'],
        ['200', '1'],
        ['200', '2'],
        ['200', '3'],
        ['200', '4'],
        ['200', '5'],
        ['200', '6'],
        ['200', '7'],
        ['200', '8'],
        ['200', '9'],
        ['200', '10'],
        ['200', '11'],
        ['200', '12'],
        ['200', '13'],
        ['200', '14'],
        ['200', '15'],
        ['200', '16'],
        ['200', '17'],
        ['200', '18'],
        ['200', '19'],
        ['200', '20'],
        ['200', '21'],
        ['200', '22'],
        ['200', '23'],
        ['200', '24'],
        ['200', '25'],
        ['200', '26'],
        ['200', '27'],
        ['200', '28'],
        ['200', '29'],
        ['200', '30'],
        ['200', '30', 'y', '1'],
        ['200', '30', 'y', '2'],
        ['200', '30', 'y', '3'],
        ['200', '30', 'y', '4'],
        ['200', '30', 'y', '5'],
        ['200', '30', 'y', '6'],
        ['200', '30', 'y', '7'],
        ['200', '30', 'y', '8'],
        ['200', '30', 'y', '9'],
        ['200', '40'],
        ['200', '40', 'y', '1'],
        ['200', '40', 'y', '2'],
        ['200', '40', 'y', '3'],
        ['200', '40', 'y', '4'],
        ['200', '40', 'y', '5'],
        ['200', '40', 'y', '6'],
        ['200', '40', 'y', '7'],
        ['200', '40', 'y', '8'],
        ['200', '40', 'y', '9'],
        ['200', '50'],
        ['200', '50', 'y', '1'],
        ['200', '50', 'y', '2'],
        ['200', '50', 'y', '3'],
        ['200', '50', 'y', '4'],
        ['200', '50', 'y', '5'],
        ['200', '50', 'y', '6'],
        ['200', '50', 'y', '7'],
        ['200', '50', 'y', '8'],
        ['200', '50', 'y', '9'],
        ['200', '60'],
        ['200', '60', 'y', '1'],
        ['200', '60', 'y', '2'],
        ['200', '60', 'y', '3'],
        ['200', '60', 'y', '4'],
        ['200', '60', 'y', '5'],
        ['200', '60', 'y', '6'],
        ['200', '60', 'y', '7'],
        ['200', '60', 'y', '8'],
        ['200', '60', 'y', '9'],
        ['200', '70'],
        ['200', '70', 'y', '1'],
        ['200', '70', 'y', '2'],
        ['200', '70', 'y', '3'],
        ['200', '70', 'y', '4'],
        ['200', '70', 'y', '5'],
        ['200', '70', 'y', '6'],
        ['200', '70', 'y', '7'],
        ['200', '70', 'y', '8'],
        ['200', '70', 'y', '9'],
        ['200', '80'],
        ['200', '80', 'y', '1'],
        ['200', '80', 'y', '2'],
        ['200', '80', 'y', '3'],
        ['200', '80', 'y', '4'],
        ['200', '80', 'y', '5'],
        ['200', '80', 'y', '6'],
        ['200', '80', 'y', '7'],
        ['200', '80', 'y', '8'],
        ['200', '80', 'y', '9'],
        ['200', '90'],
        ['200', '90', 'y', '1'],
        ['200', '90', 'y', '2'],
        ['200', '90', 'y', '3'],
        ['200', '90', 'y', '4'],
        ['200', '90', 'y', '5'],
        ['200', '90', 'y', '6'],
        ['200', '90', 'y', '7'],
        ['200', '90', 'y', '8'],
        ['200', '90', 'y', '9'],
        ['300'],
        ['300', '1'],
        ['300', '2'],
        ['300', '3'],
        ['300', '4'],
        ['300', '5'],
        ['300', '6'],
        ['300', '7'],
        ['300', '8'],
        ['300', '9'],
        ['300', '10'],
        ['300', '11'],
        ['300', '12'],
        ['300', '13'],
        ['300', '14'],
        ['300', '15'],
        ['300', '16'],
        ['300', '17'],
        ['300', '18'],
        ['300', '19'],
        ['300', '20'],
        ['300', '21'],
        ['300', '22'],
        ['300', '23'],
        ['300', '24'],
        ['300', '25'],
        ['300', '26'],
        ['300', '27'],
        ['300', '28'],
        ['300', '29'],
        ['300', '30'],
        ['300', '30', 'y', '1'],
        ['300', '30', 'y', '2'],
        ['300', '30', 'y', '3'],
        ['300', '30', 'y', '4'],
        ['300', '30', 'y', '5'],
        ['300', '30', 'y', '6'],
        ['300', '30', 'y', '7'],
        ['300', '30', 'y', '8'],
        ['300', '30', 'y', '9'],
        ['300', '40'],
        ['300', '40', 'y', '1'],
        ['300', '40', 'y', '2'],
        ['300', '40', 'y', '3'],
        ['300', '40', 'y', '4'],
        ['300', '40', 'y', '5'],
        ['300', '40', 'y', '6'],
        ['300', '40', 'y', '7'],
        ['300', '40', 'y', '8'],
        ['300', '40', 'y', '9'],
        ['300', '50'],
        ['300', '50', 'y', '1'],
        ['300', '50', 'y', '2'],
        ['300', '50', 'y', '3'],
        ['300', '50', 'y', '4'],
        ['300', '50', 'y', '5'],
        ['300', '50', 'y', '6'],
        ['300', '50', 'y', '7'],
        ['300', '50', 'y', '8'],
        ['300', '50', 'y', '9'],
        ['300', '60'],
        ['300', '60', 'y', '1'],
        ['300', '60', 'y', '2'],
        ['300', '60', 'y', '3'],
        ['300', '60', 'y', '4'],
        ['300', '60', 'y', '5'],
        ['300', '60', 'y', '6'],
        ['300', '60', 'y', '7'],
        ['300', '60', 'y', '8'],
        ['300', '60', 'y', '9'],
        ['300', '70'],
        ['300', '70', 'y', '1'],
        ['300', '70', 'y', '2'],
        ['300', '70', 'y', '3'],
        ['300', '70', 'y', '4'],
        ['300', '70', 'y', '5'],
        ['300', '70', 'y', '6'],
        ['300', '70', 'y', '7'],
        ['300', '70', 'y', '8'],
        ['300', '70', 'y', '9'],
        ['300', '80'],
        ['300', '80', 'y', '1'],
        ['300', '80', 'y', '2'],
        ['300', '80', 'y', '3'],
        ['300', '80', 'y', '4'],
        ['300', '80', 'y', '5'],
        ['300', '80', 'y', '6'],
        ['300', '80', 'y', '7'],
        ['300', '80', 'y', '8'],
        ['300', '80', 'y', '9'],
        ['300', '90'],
        ['300', '90', 'y', '1'],
        ['300', '90', 'y', '2'],
        ['300', '90', 'y', '3'],
        ['300', '90', 'y', '4'],
        ['300', '90', 'y', '5'],
        ['300', '90', 'y', '6'],
        ['300', '90', 'y', '7'],
        ['300', '90', 'y', '8'],
        ['300', '90', 'y', '9'],
        ['400'],
        ['400', '1'],
        ['400', '2'],
        ['400', '3'],
        ['400', '4'],
        ['400', '5'],
        ['400', '6'],
        ['400', '7'],
        ['400', '8'],
        ['400', '9'],
        ['400', '10'],
        ['400', '11'],
        ['400', '12'],
        ['400', '13'],
        ['400', '14'],
        ['400', '15'],
        ['400', '16'],
        ['400', '17'],
        ['400', '18'],
        ['400', '19'],
        ['400', '20'],
        ['400', '21'],
        ['400', '22'],
        ['400', '23'],
        ['400', '24'],
        ['400', '25'],
        ['400', '26'],
        ['400', '27'],
        ['400', '28'],
        ['400', '29'],
        ['400', '30'],
        ['400', '30', 'y', '1'],
        ['400', '30', 'y', '2'],
        ['400', '30', 'y', '3'],
        ['400', '30', 'y', '4'],
        ['400', '30', 'y', '5'],
        ['400', '30', 'y', '6'],
        ['400', '30', 'y', '7'],
        ['400', '30', 'y', '8'],
        ['400', '30', 'y', '9'],
        ['400', '40'],
        ['400', '40', 'y', '1'],
        ['400', '40', 'y', '2'],
        ['400', '40', 'y', '3'],
        ['400', '40', 'y', '4'],
        ['400', '40', 'y', '5'],
        ['400', '40', 'y', '6'],
        ['400', '40', 'y', '7'],
        ['400', '40', 'y', '8'],
        ['400', '40', 'y', '9'],
        ['400', '50'],
        ['400', '50', 'y', '1'],
        ['400', '50', 'y', '2'],
        ['400', '50', 'y', '3'],
        ['400', '50', 'y', '4'],
        ['400', '50', 'y', '5'],
        ['400', '50', 'y', '6'],
        ['400', '50', 'y', '7'],
        ['400', '50', 'y', '8'],
        ['400', '50', 'y', '9'],
        ['400', '60'],
        ['400', '60', 'y', '1'],
        ['400', '60', 'y', '2'],
        ['400', '60', 'y', '3'],
        ['400', '60', 'y', '4'],
        ['400', '60', 'y', '5'],
        ['400', '60', 'y', '6'],
        ['400', '60', 'y', '7'],
        ['400', '60', 'y', '8'],
        ['400', '60', 'y', '9'],
        ['400', '70'],
        ['400', '70', 'y', '1'],
        ['400', '70', 'y', '2'],
        ['400', '70', 'y', '3'],
        ['400', '70', 'y', '4'],
        ['400', '70', 'y', '5'],
        ['400', '70', 'y', '6'],
        ['400', '70', 'y', '7'],
        ['400', '70', 'y', '8'],
        ['400', '70', 'y', '9'],
        ['400', '80'],
        ['400', '80', 'y', '1'],
        ['400', '80', 'y', '2'],
        ['400', '80', 'y', '3'],
        ['400', '80', 'y', '4'],
        ['400', '80', 'y', '5'],
        ['400', '80', 'y', '6'],
        ['400', '80', 'y', '7'],
        ['400', '80', 'y', '8'],
        ['400', '80', 'y', '9'],
        ['400', '90'],
        ['400', '90', 'y', '1'],
        ['400', '90', 'y', '2'],
        ['400', '90', 'y', '3'],
        ['400', '90', 'y', '4'],
        ['400', '90', 'y', '5'],
        ['400', '90', 'y', '6'],
        ['400', '90', 'y', '7'],
        ['400', '90', 'y', '8'],
        ['400', '90', 'y', '9'],
        ['500'],
        ['500', '1'],
        ['500', '2'],
        ['500', '3'],
        ['500', '4'],
        ['500', '5'],
        ['500', '6'],
        ['500', '7'],
        ['500', '8'],
        ['500', '9'],
        ['500', '10'],
        ['500', '11'],
        ['500', '12'],
        ['500', '13'],
        ['500', '14'],
        ['500', '15'],
        ['500', '16'],
        ['500', '17'],
        ['500', '18'],
        ['500', '19'],
        ['500', '20'],
        ['500', '21'],
        ['500', '22'],
        ['500', '23'],
        ['500', '24'],
        ['500', '25'],
        ['500', '26'],
        ['500', '27'],
        ['500', '28'],
        ['500', '29'],
        ['500', '30'],
        ['500', '30', 'y', '1'],
        ['500', '30', 'y', '2'],
        ['500', '30', 'y', '3'],
        ['500', '30', 'y', '4'],
        ['500', '30', 'y', '5'],
        ['500', '30', 'y', '6'],
        ['500', '30', 'y', '7'],
        ['500', '30', 'y', '8'],
        ['500', '30', 'y', '9'],
        ['500', '40'],
        ['500', '40', 'y', '1'],
        ['500', '40', 'y', '2'],
        ['500', '40', 'y', '3'],
        ['500', '40', 'y', '4'],
        ['500', '40', 'y', '5'],
        ['500', '40', 'y', '6'],
        ['500', '40', 'y', '7'],
        ['500', '40', 'y', '8'],
        ['500', '40', 'y', '9'],
        ['500', '50'],
        ['500', '50', 'y', '1'],
        ['500', '50', 'y', '2'],
        ['500', '50', 'y', '3'],
        ['500', '50', 'y', '4'],
        ['500', '50', 'y', '5'],
        ['500', '50', 'y', '6'],
        ['500', '50', 'y', '7'],
        ['500', '50', 'y', '8'],
        ['500', '50', 'y', '9'],
        ['500', '60'],
        ['500', '60', 'y', '1'],
        ['500', '60', 'y', '2'],
        ['500', '60', 'y', '3'],
        ['500', '60', 'y', '4'],
        ['500', '60', 'y', '5'],
        ['500', '60', 'y', '6'],
        ['500', '60', 'y', '7'],
        ['500', '60', 'y', '8'],
        ['500', '60', 'y', '9'],
        ['500', '70'],
        ['500', '70', 'y', '1'],
        ['500', '70', 'y', '2'],
        ['500', '70', 'y', '3'],
        ['500', '70', 'y', '4'],
        ['500', '70', 'y', '5'],
        ['500', '70', 'y', '6'],
        ['500', '70', 'y', '7'],
        ['500', '70', 'y', '8'],
        ['500', '70', 'y', '9'],
        ['500', '80'],
        ['500', '80', 'y', '1'],
        ['500', '80', 'y', '2'],
        ['500', '80', 'y', '3'],
        ['500', '80', 'y', '4'],
        ['500', '80', 'y', '5'],
        ['500', '80', 'y', '6'],
        ['500', '80', 'y', '7'],
        ['500', '80', 'y', '8'],
        ['500', '80', 'y', '9'],
        ['500', '90'],
        ['500', '90', 'y', '1'],
        ['500', '90', 'y', '2'],
        ['500', '90', 'y', '3'],
        ['500', '90', 'y', '4'],
        ['500', '90', 'y', '5'],
        ['500', '90', 'y', '6'],
        ['500', '90', 'y', '7'],
        ['500', '90', 'y', '8'],
        ['500', '90', 'y', '9'],
        ['600'],
        ['600', '1'],
        ['600', '2'],
        ['600', '3'],
        ['600', '4'],
        ['600', '5'],
        ['600', '6'],
        ['600', '7'],
        ['600', '8'],
        ['600', '9'],
        ['600', '10'],
        ['600', '11'],
        ['600', '12'],
        ['600', '13'],
        ['600', '14'],
        ['600', '15'],
        ['600', '16'],
        ['600', '17'],
        ['600', '18'],
        ['600', '19'],
        ['600', '20'],
        ['600', '21'],
        ['600', '22'],
        ['600', '23'],
        ['600', '24'],
        ['600', '25'],
        ['600', '26'],
        ['600', '27'],
        ['600', '28'],
        ['600', '29'],
        ['600', '30'],
        ['600', '30', 'y', '1'],
        ['600', '30', 'y', '2'],
        ['600', '30', 'y', '3'],
        ['600', '30', 'y', '4'],
        ['600', '30', 'y', '5'],
        ['600', '30', 'y', '6'],
        ['600', '30', 'y', '7'],
        ['600', '30', 'y', '8'],
        ['600', '30', 'y', '9'],
        ['600', '40'],
        ['600', '40', 'y', '1'],
        ['600', '40', 'y', '2'],
        ['600', '40', 'y', '3'],
        ['600', '40', 'y', '4'],
        ['600', '40', 'y', '5'],
        ['600', '40', 'y', '6'],
        ['600', '40', 'y', '7'],
        ['600', '40', 'y', '8'],
        ['600', '40', 'y', '9'],
        ['600', '50'],
        ['600', '50', 'y', '1'],
        ['600', '50', 'y', '2'],
        ['600', '50', 'y', '3'],
        ['600', '50', 'y', '4'],
        ['600', '50', 'y', '5'],
        ['600', '50', 'y', '6'],
        ['600', '50', 'y', '7'],
        ['600', '50', 'y', '8'],
        ['600', '50', 'y', '9'],
        ['600', '60'],
        ['600', '60', 'y', '1'],
        ['600', '60', 'y', '2'],
        ['600', '60', 'y', '3'],
        ['600', '60', 'y', '4'],
        ['600', '60', 'y', '5'],
        ['600', '60', 'y', '6'],
        ['600', '60', 'y', '7'],
        ['600', '60', 'y', '8'],
        ['600', '60', 'y', '9'],
        ['600', '70'],
        ['600', '70', 'y', '1'],
        ['600', '70', 'y', '2'],
        ['600', '70', 'y', '3'],
        ['600', '70', 'y', '4'],
        ['600', '70', 'y', '5'],
        ['600', '70', 'y', '6'],
        ['600', '70', 'y', '7'],
        ['600', '70', 'y', '8'],
        ['600', '70', 'y', '9'],
        ['600', '80'],
        ['600', '80', 'y', '1'],
        ['600', '80', 'y', '2'],
        ['600', '80', 'y', '3'],
        ['600', '80', 'y', '4'],
        ['600', '80', 'y', '5'],
        ['600', '80', 'y', '6'],
        ['600', '80', 'y', '7'],
        ['600', '80', 'y', '8'],
        ['600', '80', 'y', '9'],
        ['600', '90'],
        ['600', '90', 'y', '1'],
        ['600', '90', 'y', '2'],
        ['600', '90', 'y', '3'],
        ['600', '90', 'y', '4'],
        ['600', '90', 'y', '5'],
        ['600', '90', 'y', '6'],
        ['600', '90', 'y', '7'],
        ['600', '90', 'y', '8'],
        ['600', '90', 'y', '9'],
        ['700'],
        ['700', '1'],
        ['700', '2'],
        ['700', '3'],
        ['700', '4'],
        ['700', '5'],
        ['700', '6'],
        ['700', '7'],
        ['700', '8'],
        ['700', '9'],
        ['700', '10'],
        ['700', '11'],
        ['700', '12'],
        ['700', '13'],
        ['700', '14'],
        ['700', '15'],
        ['700', '16'],
        ['700', '17'],
        ['700', '18'],
        ['700', '19'],
        ['700', '20'],
        ['700', '21'],
        ['700', '22'],
        ['700', '23'],
        ['700', '24'],
        ['700', '25'],
        ['700', '26'],
        ['700', '27'],
        ['700', '28'],
        ['700', '29'],
        ['700', '30'],
        ['700', '30', 'y', '1'],
        ['700', '30', 'y', '2'],
        ['700', '30', 'y', '3'],
        ['700', '30', 'y', '4'],
        ['700', '30', 'y', '5'],
        ['700', '30', 'y', '6'],
        ['700', '30', 'y', '7'],
        ['700', '30', 'y', '8'],
        ['700', '30', 'y', '9'],
        ['700', '40'],
        ['700', '40', 'y', '1'],
        ['700', '40', 'y', '2'],
        ['700', '40', 'y', '3'],
        ['700', '40', 'y', '4'],
        ['700', '40', 'y', '5'],
        ['700', '40', 'y', '6'],
        ['700', '40', 'y', '7'],
        ['700', '40', 'y', '8'],
        ['700', '40', 'y', '9'],
        ['700', '50'],
        ['700', '50', 'y', '1'],
        ['700', '50', 'y', '2'],
        ['700', '50', 'y', '3'],
        ['700', '50', 'y', '4'],
        ['700', '50', 'y', '5'],
        ['700', '50', 'y', '6'],
        ['700', '50', 'y', '7'],
        ['700', '50', 'y', '8'],
        ['700', '50', 'y', '9'],
        ['700', '60'],
        ['700', '60', 'y', '1'],
        ['700', '60', 'y', '2'],
        ['700', '60', 'y', '3'],
        ['700', '60', 'y', '4'],
        ['700', '60', 'y', '5'],
        ['700', '60', 'y', '6'],
        ['700', '60', 'y', '7'],
        ['700', '60', 'y', '8'],
        ['700', '60', 'y', '9'],
        ['700', '70'],
        ['700', '70', 'y', '1'],
        ['700', '70', 'y', '2'],
        ['700', '70', 'y', '3'],
        ['700', '70', 'y', '4'],
        ['700', '70', 'y', '5'],
        ['700', '70', 'y', '6'],
        ['700', '70', 'y', '7'],
        ['700', '70', 'y', '8'],
        ['700', '70', 'y', '9'],
        ['700', '80'],
        ['700', '80', 'y', '1'],
        ['700', '80', 'y', '2'],
        ['700', '80', 'y', '3'],
        ['700', '80', 'y', '4'],
        ['700', '80', 'y', '5'],
        ['700', '80', 'y', '6'],
        ['700', '80', 'y', '7'],
        ['700', '80', 'y', '8'],
        ['700', '80', 'y', '9'],
        ['700', '90'],
        ['700', '90', 'y', '1'],
        ['700', '90', 'y', '2'],
        ['700', '90', 'y', '3'],
        ['700', '90', 'y', '4'],
        ['700', '90', 'y', '5'],
        ['700', '90', 'y', '6'],
        ['700', '90', 'y', '7'],
        ['700', '90', 'y', '8'],
        ['700', '90', 'y', '9'],
        ['800'],
        ['800', '1'],
        ['800', '2'],
        ['800', '3'],
        ['800', '4'],
        ['800', '5'],
        ['800', '6'],
        ['800', '7'],
        ['800', '8'],
        ['800', '9'],
        ['800', '10'],
        ['800', '11'],
        ['800', '12'],
        ['800', '13'],
        ['800', '14'],
        ['800', '15'],
        ['800', '16'],
        ['800', '17'],
        ['800', '18'],
        ['800', '19'],
        ['800', '20'],
        ['800', '21'],
        ['800', '22'],
        ['800', '23'],
        ['800', '24'],
        ['800', '25'],
        ['800', '26'],
        ['800', '27'],
        ['800', '28'],
        ['800', '29'],
        ['800', '30'],
        ['800', '30', 'y', '1'],
        ['800', '30', 'y', '2'],
        ['800', '30', 'y', '3'],
        ['800', '30', 'y', '4'],
        ['800', '30', 'y', '5'],
        ['800', '30', 'y', '6'],
        ['800', '30', 'y', '7'],
        ['800', '30', 'y', '8'],
        ['800', '30', 'y', '9'],
        ['800', '40'],
        ['800', '40', 'y', '1'],
        ['800', '40', 'y', '2'],
        ['800', '40', 'y', '3'],
        ['800', '40', 'y', '4'],
        ['800', '40', 'y', '5'],
        ['800', '40', 'y', '6'],
        ['800', '40', 'y', '7'],
        ['800', '40', 'y', '8'],
        ['800', '40', 'y', '9'],
        ['800', '50'],
        ['800', '50', 'y', '1'],
        ['800', '50', 'y', '2'],
        ['800', '50', 'y', '3'],
        ['800', '50', 'y', '4'],
        ['800', '50', 'y', '5'],
        ['800', '50', 'y', '6'],
        ['800', '50', 'y', '7'],
        ['800', '50', 'y', '8'],
        ['800', '50', 'y', '9'],
        ['800', '60'],
        ['800', '60', 'y', '1'],
        ['800', '60', 'y', '2'],
        ['800', '60', 'y', '3'],
        ['800', '60', 'y', '4'],
        ['800', '60', 'y', '5'],
        ['800', '60', 'y', '6'],
        ['800', '60', 'y', '7'],
        ['800', '60', 'y', '8'],
        ['800', '60', 'y', '9'],
        ['800', '70'],
        ['800', '70', 'y', '1'],
        ['800', '70', 'y', '2'],
        ['800', '70', 'y', '3'],
        ['800', '70', 'y', '4'],
        ['800', '70', 'y', '5'],
        ['800', '70', 'y', '6'],
        ['800', '70', 'y', '7'],
        ['800', '70', 'y', '8'],
        ['800', '70', 'y', '9'],
        ['800', '80'],
        ['800', '80', 'y', '1'],
        ['800', '80', 'y', '2'],
        ['800', '80', 'y', '3'],
        ['800', '80', 'y', '4'],
        ['800', '80', 'y', '5'],
        ['800', '80', 'y', '6'],
        ['800', '80', 'y', '7'],
        ['800', '80', 'y', '8'],
        ['800', '80', 'y', '9'],
        ['800', '90'],
        ['800', '90', 'y', '1'],
        ['800', '90', 'y', '2'],
        ['800', '90', 'y', '3'],
        ['800', '90', 'y', '4'],
        ['800', '90', 'y', '5'],
        ['800', '90', 'y', '6'],
        ['800', '90', 'y', '7'],
        ['800', '90', 'y', '8'],
        ['800', '90', 'y', '9'],
        ['900'],
        ['900', '1'],
        ['900', '2'],
        ['900', '3'],
        ['900', '4'],
        ['900', '5'],
        ['900', '6'],
        ['900', '7'],
        ['900', '8'],
        ['900', '9'],
        ['900', '10'],
        ['900', '11'],
        ['900', '12'],
        ['900', '13'],
        ['900', '14'],
        ['900', '15'],
        ['900', '16'],
        ['900', '17'],
        ['900', '18'],
        ['900', '19'],
        ['900', '20'],
        ['900', '21'],
        ['900', '22'],
        ['900', '23'],
        ['900', '24'],
        ['900', '25'],
        ['900', '26'],
        ['900', '27'],
        ['900', '28'],
        ['900', '29'],
        ['900', '30'],
        ['900', '30', 'y', '1'],
        ['900', '30', 'y', '2'],
        ['900', '30', 'y', '3'],
        ['900', '30', 'y', '4'],
        ['900', '30', 'y', '5'],
        ['900', '30', 'y', '6'],
        ['900', '30', 'y', '7'],
        ['900', '30', 'y', '8'],
        ['900', '30', 'y', '9'],
        ['900', '40'],
        ['900', '40', 'y', '1'],
        ['900', '40', 'y', '2'],
        ['900', '40', 'y', '3'],
        ['900', '40', 'y', '4'],
        ['900', '40', 'y', '5'],
        ['900', '40', 'y', '6'],
        ['900', '40', 'y', '7'],
        ['900', '40', 'y', '8'],
        ['900', '40', 'y', '9'],
        ['900', '50'],
        ['900', '50', 'y', '1'],
        ['900', '50', 'y', '2'],
        ['900', '50', 'y', '3'],
        ['900', '50', 'y', '4'],
        ['900', '50', 'y', '5'],
        ['900', '50', 'y', '6'],
        ['900', '50', 'y', '7'],
        ['900', '50', 'y', '8'],
        ['900', '50', 'y', '9'],
        ['900', '60'],
        ['900', '60', 'y', '1'],
        ['900', '60', 'y', '2'],
        ['900', '60', 'y', '3'],
        ['900', '60', 'y', '4'],
        ['900', '60', 'y', '5'],
        ['900', '60', 'y', '6'],
        ['900', '60', 'y', '7'],
        ['900', '60', 'y', '8'],
        ['900', '60', 'y', '9'],
        ['900', '70'],
        ['900', '70', 'y', '1'],
        ['900', '70', 'y', '2'],
        ['900', '70', 'y', '3'],
        ['900', '70', 'y', '4'],
        ['900', '70', 'y', '5'],
        ['900', '70', 'y', '6'],
        ['900', '70', 'y', '7'],
        ['900', '70', 'y', '8'],
        ['900', '70', 'y', '9'],
        ['900', '80'],
        ['900', '80', 'y', '1'],
        ['900', '80', 'y', '2'],
        ['900', '80', 'y', '3'],
        ['900', '80', 'y', '4'],
        ['900', '80', 'y', '5'],
        ['900', '80', 'y', '6'],
        ['900', '80', 'y', '7'],
        ['900', '80', 'y', '8'],
        ['900', '80', 'y', '9'],
        ['900', '90'],
        ['900', '90', 'y', '1'],
        ['900', '90', 'y', '2'],
        ['900', '90', 'y', '3'],
        ['900', '90', 'y', '4'],
        ['900', '90', 'y', '5'],
        ['900', '90', 'y', '6'],
        ['900', '90', 'y', '7'],
        ['900', '90', 'y', '8'],
        ['900', '90', 'y', '9'],
        ['1000']
    ]

    def test_texto_numero(self):
        obj = Text2NumberES()
        for item, literal in enumerate(self.literales):
            resultado = obj.convert(literal)
            self.assertEqual(resultado, self.salidas[item])
        print('Finalizo...')


if __name__ == '__main__':
    unittest.main()
